### ISSUE TITLE
Latest Builds??? 

### ISSUE THREAD

**Issue by FreQRiDeR** [jacklukem/BigSurfixes#11]
Has anyone had success building installer with latest Big Sur builds? (Non beta) I can’t seem to boot my 11.2.3 basesystemfix installer? It was created without errors? Built on a separate hd partition, boots but hangs at the end? Does basesystemfix need to be updated for latest builds? Thanks!

**Comment by jacklukem** [comment]
Even if I plan to release an update, currently can simply restore through DiskUtility this 11.x DMG to an empty target: [BigSurBaseSystemfix](https://www.dropbox.com/s/p0c696odv0mujw8/bigsurbasesystemfix.dmg?dl=0)

besides DiskUtility you can use also its Apple Software Restore command line :

`sudo asr -source ~/Downloads/BigSurBaseSystemfix.dmg -erase -noverify -target /Volumes/YourUSBLabel`

- restore the BigSurBaseSystemfix.dmg to a 16 GB USB empty drive or to a 16 GB HFS+ partition (external to an APFS container)
- download any 11.x beta InstallAssistant.pkg (12,4 GB) and run it to make the unpacked apple "Install app" (other additional 12,5 GB) in its the default macOS (HighSierra, Mojave, Catalina, BigSur) Applications folder
- launch the [BigSurSharedSupportfix](https://github.com/jacklukem/BigSurfixes/releases/download/1.0/BigSurSharedSupportfix.zip) that should automatically copy the updated 12,3 GB SharedSupport.dmg (that is where - the stage2 installer is stored) to the 16 GB USB drive (that acts as an updated BaseSystemfix Installer)
- reboot from apple startup manager or any bootloader and it should work to boot "BigSurBaseSystemfix" with an updated "stage2 macOS Installer" (macOS Install Data), hence you can install current system

**Comment by FreQRiDeR** [comment]
Thank you, I was trying to do this from a usb disk I had created using your bigsurfix1 and 2 commands instead of updating a disk created from the bigsurfix image, which did not work. It worked fine when I created the usb disk from the dmg. Currently updated to 11.2.3.
