### ISSUE TITLE
Patch MBPmid2010 GPU switch issue on OCLP Big Sur

### ISSUE THREAD

**Issue by kauniss** [jacklukem/BigSurfixes#13]
What is your recommended way to patch my MBP mid 2010 (MacbookPro6,2) to address the GPU kernel panic issue, if I've installed Big Sur 11.6 through OCLP?

Some [on the MacRumors forums](https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/page-455?post=30307771#post-30307771) appear to be using your BigSurBaseSystemFix to install in combination with OCLP. What's the best way for me to do this? 

Would really appreciate some help.

Install pathway:

> Clean install of Big Sur 11.5.2 (20G95) on an internal SSD APFS volume, using OCLP 0.2.5
> Updated to Big Sur 11.6 (natively through macOS)
> Rebuilt and Repatched post-installation with OCLP 0.2.5 just to be safe
Everything working absolutely fine bar the occasional GPU panic crash.

Isn't it possible to isolate and distribute the fix you've incorporated into the the BigSurBaseSystemFix, as [fabioiop’s](https://github.com/fabioiop/MBP-2010-GPU-Panic-fix) fix did in the past?  

Grateful for your help.

**Comment by jacklukem** [comment]
You could try this, essentially I adapted and applied his Nvidia kp patch to an OCLP setup for MBP6,2 , after you made the OpenCore patcher for your machine, you should replace the attached to this path /EFI/EFI/OC/Kexts/

[AGPM-Override_Nvidia_GT330M_patch.zip](https://github.com/jacklukem/BigSurfixes/files/7246465/AGPM-Override_Nvidia_GT330M_patch.zip)

**Comment by kauniss** [comment]
Amazingly this worked. I replaced the kext using MountEfi, restarted, then subjected my poor old 6,2 to a stress test which leads to the crash, and nothing happened.

Thank you so much for this!
