### ISSUE TITLE
Please Help! I am Completely Lost!!!

### ISSUE THREAD

**Issue by ramonenghaw** [jacklukem/BigSurfixes#3]
Before I would like to thank you for the work, but I am completely lost, I created the bootable usb sticker with big sur, I applied fix 1 and 2, but on the installation screen I don't know what to do, if I apply the fixes, if I go first in hax3 fix installer, I'm completely in doubt, the disc is formatted, it's an iMac Late 2009 10.1, please help!

**Comment by jacklukem** [comment]
Use hax3 installer fix of from Utilities menu hax3 quick fix, then install BigSur on an APFS container , after reboot if you can't detect the "macOS Installer" stage2, then you need to reboot the "BaseSystem Installer" and apply "BigSurFixes stage2 installer fix" also "Install OpenCoreAPFSloader" , then at next reboot you can continue stage2 installer , after installation completes you need to reboot the "BaseSystem Installer" and apply "BigSurFixes Legacy USB patches" and maybe other graphics framebuffer fixes.

Answered also here: https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/post-29237999

**Comment by ramonenghaw** [comment]
I am trying to install again on iMac 2009 10.1 with Nvidia, but now I am facing kernel panic after stage 2 of the installation.

@jacklukem 

After stage 2, it restarts two more times, actually loads the screen with the apple logo halfway through the progress bar, and then restarts again showing the kernel panic.

Could you tell me which patches should I enable for this iMac model?

**Comment by jacklukem** [comment]
You should apply these fixes:

"BigSur stage3 installer fix"
"BigSurFixes legacy USB patches"
"BigSurFixes iSight camera fix"

**Comment by ramonenghaw** [comment]
@jacklukem 
But when do I go back to the "BaseSystem Installer" to apply the fixes? After stage 1 or stage 2? After completing stage 2, it restarts two more times, the third time imac restarts, the kernel panic screen appears.

**Comment by ramonenghaw** [comment]
@jacklukem 
![IMG_7216](https://user-images.githubusercontent.com/71452954/99321682-2b5c6380-284d-11eb-9aab-3199b8f9cd98.JPG)
Now I'm in stage 2, do I go back to the "BaseSystem Installer" right after the computer restarts or do I wait for it to restart until the kernel panic appears?

**Comment by jacklukem** [comment]
after stage2 installer there is a stage3 installer made of some auto reboot, only after you encounter a bootloop kernel panic you should apply those BigSurFixes.

**Comment by ramonenghaw** [comment]
@jacklukem 

I did exactly as you instructed, I waited for the kernel panic to appear, I returned to the "BaseSystem Installer", I applied in this order: "BigSur stage3 installer fix"
"BigSurFixes legacy USB patches"
"BigSurFixes iSight camera fix"

But it did not solve, it continues with kernel panic.

**Comment by ramonenghaw** [comment]
![IMG_7226](https://user-images.githubusercontent.com/71452954/99323913-e38c0b00-2851-11eb-8fba-4a082f602820.JPG)
![IMG_7228](https://user-images.githubusercontent.com/71452954/99323918-e4bd3800-2851-11eb-901d-f2dc864a541f.JPG)
![IMG_7227](https://user-images.githubusercontent.com/71452954/99323921-e5ee6500-2851-11eb-8c64-4b7501fef247.JPG)
![IMG_7225](https://user-images.githubusercontent.com/71452954/99323924-e686fb80-2851-11eb-9fde-261c508d5148.JPG)

**Comment by ramonenghaw** [comment]
@jacklukem This time I managed, but I also had to install OpenCore APFS loader4b, the system started, then I decided to shut down and let it start outside the opencore, and this time it started normal, without going through the opencore, the strange thing is that the first time I installed using your patch, I didn't need the opencore

**Comment by jacklukem** [comment]
To try booting without opencore, you should from opencore menu select "Restart fix" and it should boot directly from apple startup manager.

I also add that for those who can't boot the USB Installer and encountered a kernel panic after few seconds of loading, they need to use as apple bootloader another modified version of OpenCore4b1 attached here: https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/post-29138842
