### ISSUE TITLE
 2009 iMac with very slow graphics!

### ISSUE THREAD

**Issue by ramonenghaw** [jacklukem/BigSurfixes#4]
@jacklukem I installed it on the iMac, late 2009 with Nvidia 9400 video, but the graphical interface has an absurd slowness, without fluidity, I activated the isight patch that you guided, but it didn't work, I also have friends with other models of Macs 2009 that have this problem, do you think it will be circumvented, or the fact that it does not support API Metal will end the possibility of Big Sur being usable on these computers?

Thank you very much for your work.

**Comment by jacklukem** [comment]
Does iSight FaceTime webcam works ?

If you open Displays prefpane does it show the iMac picture with available screen resolutions ?

If both works then currently this is the non Metal graphics performance, but you could try this to enhance it a bit:

`defaults write com.apple.universalaccess reduceTransparency -bool true ; killall Finder`

you can also try from Accessibility menu to enable "Reduce Motion"

and maybe disable also other animations for example using these:
https://apple.stackexchange.com/questions/14001/how-to-turn-off-all-animations-on-os-x
