### ISSUE TITLE
"The update cannot be installed on this computer"

### ISSUE THREAD

**Issue by carterhamm** [jacklukem/BigSurfixes#5]
I can't find a solution on the internet, but when I download the update in the software update and go through the installer app, it won't let me select a disk to install it on. 

![Screen Shot 2020-11-24 at 11 51 50 PM](https://user-images.githubusercontent.com/75005431/100188588-1e282000-2eb0-11eb-8851-ed122813d6a7.png)

**Comment by jacklukem** [comment]
To install BigSur directly from macOS desktop, you should disable AMFI to load the ASentientBot InstallAssistant patch.

open terminal and copy paste:

`sudo nvram boot-args="-no_compat_check amfi_get_out_of_my_way=1"`

`sudo defaults write /Library/Preferences/com.apple.security.libraryvalidation.plist DisableLibraryValidation -bool true`

then reboot, apply this: https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/post-28619108

then launch the Installer and it should allow to select any disk.
