### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by carterhamm** [jacklukem/BigSurfixes#7]
I've been using this patcher for a week, and I got Big Sur, but the WiFi didn't work. I'm trying to reinstall it, but I'm having some issues. I've spent countless hours trying to fix them, but can't. Every command I run has the same issue. It returns with "Warning: you don't have any USB BigSur Installer plugged" even though I have 2 bootable Big Sur USBs plugged in. Also, how do I get the base system fix? I tried installing it but it doesn't show up as a volume or as bootable. How do I get the custom utilities menu in recovery? (and the Hax3 option) I've tried using the Hax3 command, but nothing happens. Just a few issues to look into, or maybe just issues on my part.

**Comment by jacklukem** [comment]
For the custom utilities menu, It's explained here: https://github.com/jacklukem/BigSurfixes/releases/

- from Mojave or Catalina download the 12 GB [InstallAssistant.pkg](http://swcdn.apple.com/content/downloads/19/41/001-83532-A_LN5NT1FB2Z/o4zodwe2nhyl7dh6cbuokn9deyfgsiqysn/InstallAssistant.pkg)
- launch the InstallAssistant.pkg (that automatically makes the "Install Big Sur app" on Applications folder)
- rename your 16 GB USB drive as "basesystemfix"
- make a stock USB BigSur Installer with "createinstallmedia" (about 15 minutes), open terminal:
```shell
sudo /Applications/Install\ macOS\ Big\ Sur.app/Contents/Resources/createinstallmedia --volume /Volumes/basesystemfix
```
- download this: https://forums.macrumors.com/attachments/bigsur-basesystem-legacy-usb-fix-zip.1169210/
- launch `BigSur BaseSystem Legacy USB fix`, after it completes (about 15 minutes), unplug and plug again the USB BigSur Installer, then launch `BigSur BaseSystem Legacy USB fix 2` (about 10 minutes), after done you can boot holding alt-option key from apple startup manager, from opencore or any bootloader.

**Comment by carterhamm** [comment]
And how would I create that Big Sur recovery partition? I’ve done it before, just don’t remember how.

**Comment by jacklukem** [comment]
Through those steps I wrote is made exactly my patched BigSur recovery, anyway for an easier method check here:
https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/post-29315114

**Comment by carterhamm** [comment]
I got the BigSurBaseSystemfix installed, but it's not showing as bootable. Is it supposed to be bootable or is it supposed to patch the startup disk? I don't see a recovery partition for Big Sur, and the startup disk that's showing is only compatible. How would I start that startup disk from Big Sur?

**Comment by jacklukem** [comment]
If you read my guides it is explained, that BigSurBaseSystemfix is bootable but not from Startup Disk rather after power-on hold alt-option to show the apple startup manager, to make that DMG bootable, instead of DiskUtility you can use also terminal, try these steps :

- check that in your Downloads folder there is the downloaded `BigSurBaseSystemfix.dmg` file
- rename your target USB drive as `basesystemfix`
- open terminal and copy paste:
```shell
sudo asr -source ~/Downloads/BigSurBaseSystemfix.dmg -erase -noverify -target /Volumes/basesystemfix
```
- type "y" to continue

when done, reboot, hold alt-option key for 10 seconds and the BigSurBaseSystemfix with its custom icon should show at apple startup manager, then simply select it.

**Comment by carterhamm** [comment]
Sorry about that I guess I didn’t see that in the steps, though I did read the guides. I followed the steps but it shuts down when I select it from the boot loader, and boots me back into Catalina. It shows as bootable from the disk utility menu. Any ideas?

**Comment by jacklukem** [comment]
Which Mac do you have ?

Because some Intel i3, i5 or i7 cpu require an additional OpenCore patch

**Comment by carterhamm** [comment]
I have the Mid-2010 iMac 21.5” 11,3

**Comment by jacklukem** [comment]
For that Mac to boot BigSur or its installer you need to download this: https://forums.macrumors.com/attachments/opencore4b1-zip.976384/

unzip and copy the EFI folder to any USB FAT32 drive, then reboot hold alt-option key and select OpenCoreAPFSloader4b1, then you can select BigSurBaseSystemfix and it should boot.

**Comment by carterhamm** [comment]
![image](https://user-images.githubusercontent.com/75005431/100561218-d0c7fc00-327d-11eb-9506-fba6983bef66.jpg)
I got the APFS loader working, and I tried to boot off of the BigSurBaseSystemfix like in your photo, but it still powers down when I try to boot.

**Comment by carterhamm** [comment]
![9617E3D3-A9C7-4788-93A3-8E638022CB1F](https://user-images.githubusercontent.com/75005431/100562968-d1af5c80-3282-11eb-8ddf-3cdfee4783c6.jpeg)
I was able to get the BaseSystemfix to work with the APFSBootloader, and I got the Hax3, BigSurFixes Menu and everything else to function, but once I opened Hax3 which opened the Beta, it gave me the no internet connection warning. Not sure what to do, I have an Ethernet and wireless connection.

**Comment by jacklukem** [comment]
Many are confusing the BigSurBaseSystemfix (that is only the patcher) with "BigSur Installer BaseSystem fix" (that is the full installer with patcher) for full installer you need these steps: https://github.com/jacklukem/BigSurfixes/issues/7#issuecomment-735135864
