### ISSUE TITLE
Deleting Snapshots

### ISSUE THREAD

**Issue by macOS26** [jacklukem/BigSurfixes#8]
I have had several users report that your snapshot removal tool works but mine does not. In macOS 11.1 I haven't an issue with the snapshots labelled update, but I still get users who say yours is working.

I did notice you have . "" the blank snapshot that ASentientBot came up with
and that you are using -xid instead of -uuid or -name.  I tried -xid but it says it cannot find it.

I am wondering if your using a modified .EFI for your base system or if something else enables yours to work better?

My users are running into insufficient priv which I thought was cleared up in 11.1 but I tried blessing a volume and ran into the same ins. priv. issue.

One way that I unlock the snapshot is to clone it with ASR. on the clone the snapshot is always removal. Then I might clone it back to the original disk and repeat the process. Sometimes ASR recreates a snapshot on its own.

Any info would be great and thanks for your help.

I am hard at work on bigmac2.0

**Comment by jacklukem** [comment]
Apologise for late reply, but really haven't used or updated any GitHub content during previous months, you're right on my BaseSystemfix I used both the methods, ASentientBot one tagging a blank snapshot "" and `diskutil apfs deleteSnapshot` , for me both -uuid or -xid worked, but I made that with following features:

- Hax3 dylib (this requires amfi_get_out_of_my_way=1 in nvram) to install Big Sur with an unsealed System (so it's writable also from previous macOS)
- ASentientBot patched 0xfff boot.efi (to replace on USB Big Sur Installer or even on Big Sur full installation)
- And mainly doing that snapshot removal from a BigSur Basesystem environment (or even from a stock USB Big Sur installer provided that csrutil authenticated root is disable in nvram and of course -no_compat_check)
